### ISSUE TITLE
Specifying hash algorithms in files.add doesn't work

### ISSUE THREAD

**Issue by JonKrone** [ipfs/js-ipfs#1373]
#### Subsystem:
files.add and/or IPLD

#### Type:
Bug

#### Severity:
Medium

#### Description:
`jsipfs files add --hash=<alg> ...` generates and stores an incorrect DAG.
The option to specify a different hash alg was added with https://github.com/ipfs/js-ipfs/pull/1308.

Go/JS ipfs hash differences:
![image](https://user-images.githubusercontent.com/2660142/40739372-9844feca-640b-11e8-872d-03a9daa31d36.png)
The hashes are both `keccak-512`-encoded yet we have different hashes - our object content must be different:

![image](https://user-images.githubusercontent.com/2660142/40737056-4147a3c6-6405-11e8-86a5-99512fac9c15.png)

`object get <key>` returns a serialized blob that has a `hash` different from the one requested. It seems that on unixfs import, `IPLD` is generating a blob where the `hash` is coerced from the `keccak-512` format to something else. I understood `dag-pb` to just be a style of serialization and not a hashing function itself so I'm confused what the codec of a CID holding a `keccak-512` multihash should be.

@vmx do you have some insight as to what's happening above?

I think the coercion is happening in IPLD/unixfs-engine as `unixfs-engine` uses IPLD to generate the DAG tree that unixfs later writes to the fs.

Could it be caused by something like `new CID`'s assumption that non-CID Buffers are `dag-pb` ([here](https://github.com/ipld/js-cid/blob/master/src/index.js#L78)). It may also be that IPLD can't yet handle these custom hash functions.

**Comment by JonKrone** [comment]
I don't know if this is strictly related but it strikes me as unexpected behavior of `--hash` as well:

`sha2-256` is the default hashing algorithm yet specifying it produces different output than the standard output.

![image](https://user-images.githubusercontent.com/2660142/40742426-246b4186-6414-11e8-842a-9164de338605.png)

**Comment by alanshaw** [comment]
I think @achingbrain is all over this with https://github.com/ipfs/js-ipfs/pull/1371 - @JonKrone can you verify if this PR fixes your issues?

**Comment by alanshaw** [comment]
I just realised that PR doesn't actually change any dependencies, we might need to wait for the dependent PRs to be merged.

**Comment by JonKrone** [comment]
@alanshaw cool, thanks for bringing that to my attention! That might resolve the bit about go/js having different hashes.

I think we will still be generating an incorrect DAG. `object.get` shows that a blob created via `--hash` has an incorrect encoding/format of `hash` and `links.hash`, which is different than just hashing different content.

**Comment by vmx** [comment]
IPLD doesn't support custom hash functions: https://github.com/ipld/js-ipld/blob/a6329ce30e4b21bb2d0852326cfd55753c33b353/src/index.js#L239

**Comment by JonKrone** [comment]
Thanks for the confirmation @vmx. Does this mean that we aren't currently able to support https://github.com/ipfs/js-ipfs/pull/1308? Something like: `jsipfs files add --hash=sha3-512`

**Comment by vmx** [comment]
@JonKrone I'd be surprised if it would work.

**Comment by JonKrone** [comment]
@alanshaw As this feature is broken and has a more involved fix with no timeline, I think it should be reverted or we should otherwise indicate that it's not ready for use.

**Comment by alanshaw** [comment]
@JonKrone I believe this is now resolved - #1371 was merged and IPLD now supports specifying the hash algorithm https://github.com/ipld/js-ipld/pull/133

Are you able to double check?

**Comment by JonKrone** [comment]
Hey @alanshaw!

I was excited when I saw this but after fresh installs of the most recent go and js versions, I still see mismatched hashes for the `add --hash=keccak-512` command and see that the `object` stored by js-ipfs still lists a CIDv0 `hash`

**Comment by achingbrain** [comment]
@JonKrone which version are you using?  I see CIDv1 with `--hash=keccak-512`:

```sh
$ jsipfs add foo.txt --hash=keccak-512
added zBurK9v3LNabF2nosKPjnPWznRAQRjAEuRLx2Mbsa2qVtrYRA48dYybAXUGsXUhB1KQipPnYie1mQmnnxYik1DHThzReM foo.txt
$ jsipfs --version
0.31.1
```

**Comment by JonKrone** [comment]
@achingbrain Yep! And that part works! What seems to fail is:

`jsipfs object get` of a CIDv1 returns a blob with a v0 `hash` property.

I think the part of the add stream where this happens is when `unix-fs` passes off to IPLD, as `unix-fs` is storing the object under the correct CID but the blob it stores is incorrect.

I'm using `0.31.2`.
