### ISSUE TITLE
Can't establish a connection to the server at ws://...

### ISSUE THREAD

**Issue by deanvaessen** [ipfs/js-ipfs#1732]
- **Version**: 0.33.1
- **Platform**: Win 10 x64 (Tested with Firefox Developer Edition 64.0b12 (64-bit) and Brave 0.25.2)

#### Description:
Hi, I am trying ipfs with 3box (3box.io) and keep getting ipfs connection issues right when my application starts. I installed 3box (which uses ipfs as a dependency), and immediately I am getting server connection errors. I have also tried to manually add newer versions of ipfs, ipfs-api and libp2p but I am still encountering the same issues. Here's a log:
`Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ipfs.3box.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node0.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://node1.preload.ipfs.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/. bundle.js line 27140 > eval:18:15
`

**Comment by alanshaw** [comment]
This seems to be working for the majority of nodes now but `ams-1.bootstrap.libp2p.io` is still down.

<img width="1319" alt="screenshot 2018-11-29 at 11 00 37" src="https://user-images.githubusercontent.com/152863/49217654-07848680-f3c6-11e8-8946-5c6b25d9d279.png">

**Comment by kyledrake** [comment]
AMS issue is resolved, it was indeed having issues (it was known, our monitoring picked it up). I didn't see any issues with our other preload servers, but if you couldn't connect to wss://ipfs.3box.io/ either I wonder if there's something going on with your network connection? We don't control those servers and having all of them go down at once is pretty unexpected.

**Comment by deanvaessen** [comment]
Had another go but strange enough, I'm still encountering the same issues. 

> but if you couldn't connect to wss://ipfs.3box.io/ either I wonder if there's something going on with your network connection? We don't control those servers and having all of them go down at once is pretty unexpected.

I thought something similar, but I don't have any other issues with other websites. I can try from a different location and will report back once I have done so.

**Comment by SaifRehman** [comment]
I am having the same issue, any idea why ?
