### ISSUE TITLE
Empty streams do not result in the "empty CID"

### ISSUE THREAD

**Issue by ribasushi** [ipfs/js-ipfs#2956]
What I get with `0.41.2`
```
echo -n | jsipfs add -nq | wc
       0       0       0
```

What I expected:
```
echo -n | ../ipfs add -nq 
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH

echo -n | ../ipfs add -nq --inline
bafyaabqkaqeaegaa
```

**Comment by bluelovers** [comment]
maybe because empty streams mean ''

**Comment by achingbrain** [comment]
For me master is consistent with go-ipfs, so it'll be fixed in the next release.

```console
$ echo -n | ipfs add -nq
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
$ echo -n | jsipfs add -nq
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
```

@ribasushi if you like you can get a head start by using the RC with `npm install -g ipfs@next`

**Comment by ribasushi** [comment]
@achingbrain actually it got worse :(

```
admin:~/devel/go-ipfs$ npm install -g ipfs@next
...
+ ipfs@0.42.2-rc.4

admin:~/devel/go-ipfs$ jsipfs --version
0.42.2-rc.4
```

✅ WORKS
```
admin:~/devel/go-ipfs$ echo -n | cmd/ipfs/ipfs add -nq 
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
admin:~/devel/go-ipfs$ echo -n | jsipfs add -nq 
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
```

❌ FAILS
```
admin:~/devel/go-ipfs$ echo -n | cmd/ipfs/ipfs add -nq --cid-version=1
bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku
admin:~/devel/go-ipfs$ echo -n | jsipfs add -nq --cid-version=1
bafybeif7ztnhq65lumvvtr4ekcwd2ifwgm3awq4zfr3srh462rwyinlb4y
```

✅ WORKS
```
admin:~/devel/go-ipfs$ echo -n | cmd/ipfs/ipfs add -nq --cid-version=1 --trickle
bafybeif7ztnhq65lumvvtr4ekcwd2ifwgm3awq4zfr3srh462rwyinlb4y
admin:~/devel/go-ipfs$ echo -n | jsipfs add -nq --cid-version=1 --trickle
bafybeif7ztnhq65lumvvtr4ekcwd2ifwgm3awq4zfr3srh462rwyinlb4y
```

⚔️ HANGS
```
admin:~/devel/go-ipfs$ echo -n | cmd/ipfs/ipfs add -nq --chunker=rabin
QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH
admin:~/devel/go-ipfs$ echo -n | timeout 5 jsipfs add -nq --chunker=rabin
[@ Sat 04:27:54.690]
[$?==124/    5.025s]
```

**Comment by jacobheun** [comment]
This is still an issue although the fail cases have changed a bit in the most recent version.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
